// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MindScale - Testes Mentais Interativos",
  description: "Descubra mais sobre sua mente com nossos testes científicos interativos de QI e traços de autismo. Análises precisas e resultados detalhados.",
  keywords: "teste de QI, teste de autismo, testes mentais, psicologia, inteligência, análise comportamental",
  authors: [{ name: "MindScale" }],
  viewport: "width=device-width, initial-scale=1",
  robots: "index, follow",
  openGraph: {
    title: "MindScale - Testes Mentais Interativos",
    description: "Explore seu potencial mental com testes científicos interativos",
    type: "website",
    locale: "pt_BR",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}